export const ACHIEVEMENTS = {
  FIRST_CAPTURE: {
    id: 'first_capture',
    name: 'Primeira Captura',
    description: 'Registre seu primeiro peixe.',
    icon: '🎣',
    category: 'capturas',
    requirement: { type: 'captures', value: 1 },
  },
  TEN_FISHES: {
    id: 'ten_fishes',
    name: '10 Peixes',
    description: 'Registre 10 capturas.',
    icon: '🐟',
    category: 'capturas',
    requirement: { type: 'captures', value: 10 },
  },
  FIFTY_FISHES: {
    id: 'fifty_fishes',
    name: '50 Peixes',
    description: 'Registre 50 capturas.',
    icon: '🐟',
    category: 'capturas',
    requirement: { type: 'captures', value: 50 },
  },
  HUNDRED_FISHES: {
    id: 'hundred_fishes',
    name: '100 Peixes',
    description: 'Registre 100 capturas.',
    icon: '🏆',
    category: 'capturas',
    requirement: { type: 'captures', value: 100 },
  },
  FIVE_HUNDRED_FISHES: {
    id: 'five_hundred_fishes',
    name: '500 Peixes',
    description: 'Registre 500 capturas.',
    icon: '🥇',
    category: 'capturas',
    requirement: { type: 'captures', value: 500 },
  },
  THOUSAND_FISHES: {
    id: 'thousand_fishes',
    name: '1000 Peixes',
    description: 'Registre 1000 capturas.',
    icon: '👑',
    category: 'capturas',
    requirement: { type: 'captures', value: 1000 },
  },
  FIRST_TUCUNARE: {
    id: 'first_tucunare',
    name: 'Primeiro Tucunaré',
    description: 'Capture seu primeiro tucunaré.',
    icon: '🐠',
    category: 'espécies',
    requirement: { type: 'species_count', value: 'tucunaré', count: 1 },
  },
  FIRST_TRAIRA: {
    id: 'first_traira',
    name: 'Primeira Traíra',
    description: 'Capture sua primeira traíra.',
    icon: '🐠',
    category: 'espécies',
    requirement: { type: 'species_count', value: 'traíra', count: 1 },
  },
  FIRST_DOURADO: {
    id: 'first_dourado',
    name: 'Primeiro Dourado',
    description: 'Capture seu primeiro dourado.',
    icon: '✨',
    category: 'espécies',
    requirement: { type: 'species_count', value: 'dourado', count: 1 },
  },
  NIGHT_FISHING: {
    id: 'night_fishing',
    name: 'Pesca Noturna',
    description: 'Registre uma captura entre 20h e 6h.',
    icon: '🌙',
    category: 'momentos',
    requirement: { type: 'time', value: 'night' },
  },
  RAIN_FISHING: {
    id: 'rain_fishing',
    name: 'Pesca na Chuva',
    description: 'Preparada para eventos marcados como chuva.',
    icon: '🌧️',
    category: 'momentos',
    requirement: { type: 'manual', value: true },
  },
  EARLY_BIRD: {
    id: 'early_bird',
    name: 'Madrugador',
    description: 'Registre uma captura entre 5h e 7h.',
    icon: '🌅',
    category: 'momentos',
    requirement: { type: 'time', value: 'early_morning' },
  },
  GIANT_HUNTER: {
    id: 'giant_hunter',
    name: 'Caçador de Gigantes',
    description: 'Capture um peixe acima de 50 kg.',
    icon: '🦈',
    category: 'recordes',
    requirement: { type: 'largest_fish', value: 50 },
  },
  RIVER_MASTER: {
    id: 'river_master',
    name: 'Mestre dos Rios',
    description: 'Registre capturas em 10 locais diferentes.',
    icon: '🗺️',
    category: 'recordes',
    requirement: { type: 'different_locations', value: 10 },
  },
  RECORD_HOLDER: {
    id: 'record_holder',
    name: 'Recordista',
    description: 'Capture um peixe acima de 80 kg.',
    icon: '🥇',
    category: 'recordes',
    requirement: { type: 'largest_fish', value: 80 },
  },
};

export const ACHIEVEMENT_CATEGORIES = ['capturas', 'espécies', 'momentos', 'recordes'];

export const getAchievementById = (achievementId) =>
  Object.values(ACHIEVEMENTS).find((achievement) => achievement.id === achievementId) || null;

export const getAllAchievements = () => Object.values(ACHIEVEMENTS);
