export const FISH_SPECIES = [
  'Tucunaré',
  'Traíra',
  'Dourado',
  'Piranha',
  'Cumbaca',
  'Pirarucu',
  'Jacaré-açu',
  'Pacu',
  'Tilápia',
  'Matrinxã',
  'Aruanã',
  'Tambaqui',
  'Barbado',
  'Surubim',
  'Outro',
];

export const STATES = [
  'Acre',
  'Alagoas',
  'Amapá',
  'Amazonas',
  'Bahia',
  'Ceará',
  'Distrito Federal',
  'Espírito Santo',
  'Goiás',
  'Maranhão',
  'Mato Grosso',
  'Mato Grosso do Sul',
  'Minas Gerais',
  'Pará',
  'Paraíba',
  'Paraná',
  'Pernambuco',
  'Piauí',
  'Rio de Janeiro',
  'Rio Grande do Norte',
  'Rio Grande do Sul',
  'Rondônia',
  'Roraima',
  'Santa Catarina',
  'São Paulo',
  'Sergipe',
  'Tocantins',
];

export const NOTIFICATION_TYPES = {
  SUCCESS: 'success',
  ERROR: 'error',
  WARNING: 'warning',
  INFO: 'info',
};
