export const TITLES = {
  FISHING_BEGINNER: {
    id: 'fishing_beginner',
    name: 'Pescador Iniciante',
    description: 'Seu primeiro passo na comunidade FishRank.',
    icon: '🎣',
    type: 'regular',
    requirement: { type: 'captures', value: 1 },
  },
  FISHING_EXPERIENCED: {
    id: 'fishing_experienced',
    name: 'Pescador Experiente',
    description: 'Consistência comprovada nas pescarias.',
    icon: '🐟',
    type: 'regular',
    requirement: { type: 'captures', value: 10 },
  },
  KING_OF_FISHING: {
    id: 'king_of_fishing',
    name: 'Rei da Pesca',
    description: 'Cinquenta capturas e muita história para contar.',
    icon: '👑',
    type: 'regular',
    requirement: { type: 'captures', value: 50 },
  },
  LEGENDARY_FISHERMAN: {
    id: 'legendary_fisherman',
    name: 'Pescador Lendário',
    description: 'Uma lenda das águas.',
    icon: '✨',
    type: 'regular',
    requirement: { type: 'captures', value: 100 },
  },
  LIVING_LEGEND: {
    id: 'living_legend',
    name: 'Lenda Viva',
    description: 'Seu nome já circula entre os pescadores.',
    icon: '⭐',
    type: 'legendary',
    requirement: { type: 'captures', value: 200 },
  },
  GIANT_HUNTER: {
    id: 'giant_hunter',
    name: 'Caçador de Gigantes',
    description: 'Especialista em peixes acima de 50 kg.',
    icon: '🦈',
    type: 'regular',
    requirement: { type: 'largest_fish', value: 50 },
  },
  TRAIRA_MASTER: {
    id: 'traira_master',
    name: 'Mestre das Traíras',
    description: 'A traíra já conhece o seu anzol.',
    icon: '🐠',
    type: 'regular',
    requirement: { type: 'species_count', value: 'traíra', count: 1 },
  },
  TUCUNARE_KING: {
    id: 'tucunare_king',
    name: 'Rei do Tucunaré',
    description: 'Tucunaré no registro, respeito no ranking.',
    icon: '🐠',
    type: 'regular',
    requirement: { type: 'species_count', value: 'tucunaré', count: 1 },
  },
  WATERS_LORD: {
    id: 'waters_lord',
    name: 'Senhor das Águas',
    description: 'Meia tonelada de histórias somadas.',
    icon: '🌊',
    type: 'regular',
    requirement: { type: 'total_weight', value: 500 },
  },
  WATERS_EMPEROR: {
    id: 'waters_emperor',
    name: 'Imperador das Águas',
    description: 'Mil quilos registrados no FishRank.',
    icon: '🏆',
    type: 'legendary',
    requirement: { type: 'total_weight', value: 1000 },
  },
  FISHING_MYTH: {
    id: 'fishing_myth',
    name: 'Mito da Pesca',
    description: 'Quinhentas capturas publicadas.',
    icon: '🌟',
    type: 'legendary',
    requirement: { type: 'captures', value: 500 },
  },
  SUPREME_MASTER: {
    id: 'supreme_master',
    name: 'Mestre Supremo',
    description: 'Mil capturas. Sem atalhos.',
    icon: '💎',
    type: 'legendary',
    requirement: { type: 'captures', value: 1000 },
  },
  CUMBACA_FISHERMAN: {
    id: 'cumbaca_fisherman',
    name: 'Pescador de Cumbaca',
    description: 'Especialista em pegar o peixe que ninguém queria.',
    icon: '😄',
    type: 'humorous',
    requirement: { type: 'species_count', value: 'cumbaca', count: 50 },
  },
  TANGLED_KING: {
    id: 'tangled_king',
    name: 'Rei do Enrosco',
    description: 'Humor para quem já aceitou o próprio estilo.',
    icon: '🪢',
    type: 'humorous',
    requirement: { type: 'manual', value: true },
  },
  UNLUCKY_OFFICIAL: {
    id: 'unlucky_official',
    name: 'Azarado Oficial',
    description: 'Quando a pescaria vira memória mesmo sem troféu.',
    icon: '☘️',
    type: 'humorous',
    requirement: { type: 'manual', value: true },
  },
  CUMBACA_MAGNET: {
    id: 'cumbaca_magnet',
    name: 'Ímã de Cumbaca',
    description: 'As cumbacas te encontram primeiro.',
    icon: '🧲',
    type: 'humorous',
    requirement: { type: 'species_count', value: 'cumbaca', count: 100 },
  },
};

export const TITLE_CATEGORIES = {
  regular: 'Títulos de Progresso',
  legendary: 'Títulos Lendários',
  humorous: 'Títulos Humorísticos',
};

export const getTitleById = (titleId) =>
  Object.values(TITLES).find((title) => title.id === titleId) || null;

export const getAllTitles = () => Object.values(TITLES);
